version: '3.5'

services:
  todo_db:
    build:
      context: .
      dockerfile: ./docker/database/Dockerfile
    container_name: "daily-tasks-db"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
  backend_prd:
    container_name: "daily-tasks-server-prd"
    image: "daily-tasks-server-backend:${APP_VERSION}"
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
      target: production
    ports:
      - "5000:5000"
    depends_on:
      - todo_db
    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_LOGIN=${EMAIL_LOGIN}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_SENDER=${EMAIL_SENDER}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - JWT_EXPIRATION_TIME_IN_SECONDS=${JWT_EXPIRATION_TIME_IN_SECONDS}
      - JWT_REFRESH_TOKEN_EXPIRATION_IN_DAYS=${JWT_REFRESH_TOKEN_EXPIRATION_IN_DAYS}
      - JWT_ACCESS_TOKEN_EXPIRATION_IN_MINUTES=${JWT_ACCESS_TOKEN_EXPIRATION_IN_MINUTES}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    network_mode: host

networks:
  default:
    driver: bridge

volumes:
  db_data:
    driver: local